### ISSUE TITLE
As an admin I want to see all current megathread requests so that I can accept, deny, or skip them for now.

### ISSUE THREAD

**Issue by chrisXchen** [software-assignments-spring2022/final-project-ranked#42]
## Estimation of work
- TBD

## Acceptance criteria
- [ ] foo
- [ ] bar
- [ ] baz
- [ ] etc

**Comment by M2JT** [comment]
related with task #55 for sprint 2

**Comment by M2JT** [comment]
related with task #86 for sprint 3
